### ISSUE TITLE
Meta support

### ISSUE THREAD

**Issue by dlq84** [olosegres/jsona#14]
Hi, it would be great if this lib could support meta information. As it is now that information is just ignored during deserialization

http://jsonapi.org/format/#document-meta

**Comment by olosegres** [comment]
@dlq84 Hi, what kind of support do you mean? Add argument to pass meta to `serialize`?

**Comment by dlq84** [comment]
I think it's only relevant during deserialization, ie the server API is the party that is adding such information.

So basically have a `setMeta()` in the `IModelPropertiesMapper` so it can be implemented in the user implemented property mapper and maybe even in the default `JsonPropertiesMapper`

Regards

**Comment by olosegres** [comment]
@dlq84 Ok, I'll merge it with some additions soon

**Comment by anjalirana** [comment]
@olosegres Hi, was this one merged?

**Comment by olosegres** [comment]
@dlq84 @anjalirana @ggagosh
Hi!

It has been merged, available since version 1.1.6, sorry for delay

p.s. It's not cover support meta in relationship object http://jsonapi.org/format/#document-resource-object-relationships tell me if you need it

**Comment by aganov** [comment]
@olosegres Can we have the same implementation for `data.links`?
http://jsonapi.org/format/#document-links


```js
setLinks(model: TJsonaModel, meta: TAnyKeyValueObject): void;
```

```js

if (data.links) {
  this.pm.setLinks(model, data.links);
}
```

Thanks!

**Comment by olosegres** [comment]
@aganov 
Added in 1.1.8

**Comment by olosegres** [comment]
@dlq84 @anjalirana @ggagosh

Support of meta in relationship object added in 1.1.8 too
