### ISSUE TITLE
switchCasePropertyMappers from Javascript

### ISSUE THREAD

**Issue by pwim** [olosegres/jsona#15]
I noticed that there's a switchCasePropertyMappers.ts which seems to provide a way to camelize properties. However, that file only exists in src, and there is no compiled lib/switchCasePropertyMappers.js. Was this an oversight, or can I only use that if I'm using typescript?

**Comment by olosegres** [comment]
@pwim You're right, it was oversight. Fixed in 1.1.9

**Comment by pwim** [comment]
Thanks!
