### ISSUE TITLE
Deserializing Relationships With Embedded Data

### ISSUE THREAD

**Issue by steven-mays** [olosegres/jsona#18]
I want to deserialize a relationship with embedded data. Do you have a recommended way of handling that within `jsona`?

Example:
```
{
    links: {},
    data: {
      type: 'characters',
      id: '1234',
      attributes: {
        name: 'Mickey'
      },
      relationships: {
        skills: {
          data: [{
            type: 'skills',
            id: 'swords',
            attributes: {
              level: 20
            }
          }, {
            type: 'skills',
            id: 'bows',
            attributes: {
              level: 3
            }
          }]
        }
      }
    }
  }
```

Deserializes to:
```
{ type: 'characters',
      id: '1234',
      name: 'Mickey',
      skills: 
       [ { type: 'skills', id: 'swords' },
         { type: 'skills', id: 'bows' } ],
      relationshipNames: [ 'skills' ] }
```

What I'm looking to for:
```
{ type: 'characters',
      id: '1234',
      name: 'Mickey',
      skills: 
       [ { type: 'skills', id: 'swords', level: 20 },
         { type: 'skills', id: 'bows', level: 3 } ],
      relationshipNames: [ 'skills' ] }
```

**Comment by olosegres** [comment]
Actually, embedded data, like attributes should be in ‘included’ part of json. Your approach is a violation of the spetification.

But yo can do it with jsona, by creating your own [propertyMappers](https://github.com/olosegres/jsona/blob/master/src/simplePropertyMappers.ts)

See how customize in the end of [README](https://github.com/olosegres/jsona/blob/master/README.md)

**Comment by steven-mays** [comment]
@olosegres Any tips you can give with writing a propertyMapper in javascript within a node project?

**Comment by olosegres** [comment]
I was wrong about possibility to do it with custom propertyMappers, to make it work you need to do changes to the library, but this is a violation of the specification, so I offer to fork jsona and make changes you need there.
