### ISSUE TITLE
Throws `undefined` error when relationships are not included

### ISSUE THREAD

**Issue by Redsandro** [olosegres/jsona#2]
It's legal in JSON-API to exclude relationships. In fact, relationships should only be included when explicitly requested using the `include=` querystring.

However, `jsona` throws an `undefined` error when a certain relationship is not included.

**Comment by olosegres** [comment]
Which high-level method did you use? (deserialize or denormalizeReduxObject?)

**Comment by Redsandro** [comment]
I think it was deserialize.

(Full disclosure: I'm working server-side. Someone else in the team used `jsona` client-side and prefered making their own implementation. I asked why.)

**Comment by olosegres** [comment]
@Redsandro I will fix it till tomorrow

**Comment by olosegres** [comment]
@Redsandro Fixed

**Comment by Redsandro** [comment]
:+1: 

Patch version on npm?

**Comment by olosegres** [comment]
@Redsandro Yeah, v1.0.10
