### ISSUE TITLE
Links are ignored during deserialization

### ISSUE THREAD

**Issue by FeliciousX** [olosegres/jsona#22]
the default `simplePropertyMappers` does not work with pagination when `body` contains `link`

example..

```json
{
  "meta": {
    "totalPages": 13
  },
  "data": [
    {
      "type": "articles",
      "id": "3",
      "attributes": {
        "title": "JSON:API paints my bikeshed!",
        "body": "The shortest article. Ever.",
        "created": "2015-05-22T14:56:29.000Z",
        "updated": "2015-05-22T14:56:28.000Z"
      }
    }
  ],
  "links": {
    "self": "http://example.com/articles?page[number]=3&page[size]=1",
    "first": "http://example.com/articles?page[number]=1&page[size]=1",
    "prev": "http://example.com/articles?page[number]=2&page[size]=1",
    "next": "http://example.com/articles?page[number]=4&page[size]=1",
    "last": "http://example.com/articles?page[number]=13&page[size]=1"
  }
}
```
when deserialized, will be

```typescript
[ { type: 'articles',
    id: '3',
    title: 'JSON:API paints my bikeshed!',
    body: 'The shortest article. Ever.',
    created: '2015-05-22T14:56:29.000Z',
    updated: '2015-05-22T14:56:28.000Z' } ]
```

I see that `setLinks` exists on the `simplePropertyMapper` [here](https://github.com/olosegres/jsona/blob/37f636823492fb3cfd1ce45a21d31a3953241529/src/simplePropertyMappers.ts#L114-L116)

but it seems that only `links` inside `data` will be checked, but not the `body.links` ( which is where `links` will exist if it's for pagination )

**Comment by olosegres** [comment]
@FeliciousX @stilio @kartikluke

Hi, do you have any ideas how should look deserialized output with root meta and links, when there is collection or one item in data?

Like this?
```javascript
type TDeserialized = {
  data: TJsonaModel | TJsonaModel[] | null,
  meta: TAnyKeyValueObject,
  links: TLinks,
};
```

**Comment by konovalov-nk** [comment]
The problem is still relevant @olosegres. I'm looking forward to migrate from previously used jsonapi deserializer library because it doesn't support circular relationships properly and maintainer seems to be very busy 🙂

I believe you should do it like that:

```typescript
type TDeserialized = {
  data: TJsonaModel | TJsonaModel[] | null, // "stuff" isn't very descriptive
  meta: TAnyKeyValueObject,
  links: TLinks,
};
```

**Comment by olosegres** [comment]
@konovalov-nk 
I use "stuff" to show that it is not "data" from json, in the code they are found nearby

**Comment by olosegres** [comment]
@konovalov-nk 
Such an update creates a number of inconveniences, the main of which is the difficulty of updating to new versions for those already using jsona.

Why you can't extend Jsona class in your code or just wrap `jsona.deserialize` in function, that will add links and meta to output?

**Comment by konovalov-nk** [comment]
Yup that's exactly what we are doing now but we also would like to deeply camelize all keys (even nested ones) we're receiving from the back-end. Otherwise, we have to use some kind of pre-processing, like `transformResponse` from the `axios`. It works, but workaround seems to be a little hacky.

This could be an option and surely doesn't have to be a default behaviour. It's more about the vision for the `jsona`. Do you feel like it should stick to the JSON:API standard and implement specifications exactly like visioned? Or rather implement things a bit different using your/community perspective?

**Comment by olosegres** [comment]
Jsona is a tool to simplify the work with standardized data. Everything inside the meta is not standardized and jsona cannot take into account all the special cases. Thus, everything that is not standardized will look a bit hacky, I think this is normal.

But if you see a way to make jsona better, then welcome, we can consider your PRs :)
