### ISSUE TITLE
TS Types: Using `super` in custom model properties mapper requires type casting

### ISSUE THREAD

**Issue by ahx** [olosegres/jsona#24]
I am a TypeScript noob, so excuse me if I am doing things totally wrong here.

I would like to use the `modelPropertiesMapper` option to implement custom format for "special" attribute. I only want to change that one "special" field and don't want to think about other things so I am exteding the `ModelPropertiesMapper` in and would like to use `super`. Then I see this error:

<img width="1111" alt="screen shot 2018-11-15 at 23 42 14" src="https://user-images.githubusercontent.com/8669/48586563-8e4e5380-e930-11e8-8261-c9c5d40b8b07.png">

Of course this just works if I use type casting, but It feels wrong:

<img width="874" alt="screen shot 2018-11-15 at 23 42 29" src="https://user-images.githubusercontent.com/8669/48586564-8e4e5380-e930-11e8-8087-78cfd4339491.png">

I guess this is because when using the npm package the generated types tell me that `getAttributes` always return `{}`, which is not helpful. 

Suggestion: Can we change the return type of `getAttributes` to `any` or `TAnyKeyValueObject`?

**Comment by olosegres** [comment]
It will be very useful for you to read whole this page, but you can search keywords “pet is Fish” for one of possible solutions
https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Comment by ahx** [comment]
Thanks for the heads up. So I guess using type casting here is fine.
