### ISSUE TITLE
switchChar meta to camelCased

### ISSUE THREAD

**Issue by nreva** [olosegres/jsona#30]
Hi, it would be great if switchChar can convert meta to camelCased.

`const products = new Jsona({
          modelPropertiesMapper: new SwitchCaseModelMapper(),
          jsonPropertiesMapper: new SwitchCaseJsonMapper({ switchChar: '_' }),
}).deserialize(data);`

![Снимок экрана 2019-05-14 в 16 45 24](https://user-images.githubusercontent.com/36101407/57702996-d512d100-7667-11e9-8fef-8e8ed49c7be8.png)

**Comment by olosegres** [comment]
Added in 1.5.0
