### ISSUE TITLE
Keep relationship links when deserializing

### ISSUE THREAD

**Issue by bondzula** [olosegres/jsona#37]
Hi, like the title suggests I was wondering if there was any way to keep the relationship links after deserializing data. My use case is rather simple I would say, as I need deserialization in almost every part of my app, the easiest way for me was implementing response interceptor on axios instance, and getting deserialized data on every request. However, there are few parts where I want to be able to load relationships separately on user request and those links come in handy. I've already kinda solved the issue by making the interceptor optional, and when I do need those links, I disable it and deserialize after getting the links, but I'm not really happy with that approach. I could also append those links to deserialize data inside the interceptor but I'm not completely sure how that would look like on a collection of resources, so just wanted to make sure whatever or not this was possible with jsona perhaps. Any help would be appreciated.

**Comment by olosegres** [comment]
@bondzula 
Hi, I have not encountered such a case, so I can not tell you something specific.
But you can create your own property mapper and describe how to work with links.
Look at [this line](../blob/d849dc13f4a85c92dae765918fb0039ed9e8c36c/src/simplePropertyMappers.ts#L143) and read "Customize" section of [README](../blob/master/README.md#customize).
