### ISSUE TITLE
`meta` property in relationship is dropped when deserializing

### ISSUE THREAD

**Issue by ericwong3** [olosegres/jsona#39]
According to the spec, a relationship's `data` can contain `meta`, i.e. `jsonApiObject.data[*].relationships.<field>.data[*].meta` can exists. (Also applies to singular `data`/response object)

Or more formally, according to the specification:
1. Top Level contains `data`, which must be either single or array of "resource objects"
1. Resource Objects may contain `relationships`, which is a "relationships object"
1. (Each) Relationship Object contains `data`, which is a "resource linkage"
1. Resource Linkage can be either single or array of "resource identifier object"
1. Resource Identifier Objects may include `meta`

In my case which uses Jsona with Drupal, problem arises because Drupal uses individual relationship object's meta to transmit image alt texts. As a result the alt text is lost.

As an example, this is a stripped JSON:API response from Drupal:
```json
{
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": {
          "href": "http://jsonapi.org/format/1.0/"
        }
      }
    }
  },
  "data": [{
    "type": "node--site_configuration",
    "id": "f8895943-7f51-451b-bb8f-a479853f1b4b",
    "links": {
      "self": {
        "href": "http://acmecorp-cms.lndo.site/en/jsonapi/node/site_configuration/f8895943-7f51-451b-bb8f-a479853f1b4b?resourceVersion=id%3A230"
      }
    },
    "attributes": {
      "langcode": "en",
      "title": "Site Configuration"
    },
    "relationships": {
      "field_logo": {
        "data": {
          "type": "file--file",
          "id": "551ec1b9-b0c6-4649-bb7c-b6ebb09354ff",
          "meta": {
            "alt": "ACME Corp Logo",
            "title": "",
            "width": 206,
            "height": 278
          }
        },
        "links": {
          "related": {
            "href": "http://acmecorp-cms.lndo.site/en/jsonapi/node/site_configuration/f8895943-7f51-451b-bb8f-a479853f1b4b/field_logo?resourceVersion=id%3A230"
          },
          "self": {
            "href": "http://acmecorp-cms.lndo.site/en/jsonapi/node/site_configuration/f8895943-7f51-451b-bb8f-a479853f1b4b/relationships/field_logo?resourceVersion=id%3A230"
          }
        }
      }
    }
  }],
  "included": [{
    "type": "file--file",
    "id": "551ec1b9-b0c6-4649-bb7c-b6ebb09354ff",
    "links": {
      "self": {
        "href": "http://acmecorp-cms.lndo.site/en/jsonapi/file/file/551ec1b9-b0c6-4649-bb7c-b6ebb09354ff"
      }
    },
    "attributes": {
      "langcode": "en",
      "uri": {
        "value": "public://2020-07/acmecorp-logo-colour-2x.png",
        "url": "http://acmecorp.oss-cn-hongkong.aliyuncs.com/s3fs-public/2020-07/acmecorp-logo-colour-2x.png"
      },
      "filemime": "image/png",
      "filesize": 54952
    }
  }]
}
```

Notice there is `alt: "ACME Corp Logo"` in `meta` object in `data[0].relationships.field_logo.data`.

If we try to parse it with a simple Jsona code, i.e.

```js
const Jsona = require('jsona').default;

const dataFormatter = new Jsona();

const data = require('./drupal-jsonapi-response.json');

console.log(JSON.stringify(dataFormatter.deserialize(data), null, 2));
```

The output is

```json
[
  {
    "type": "node--site_configuration",
    "id": "f8895943-7f51-451b-bb8f-a479853f1b4b",
    "langcode": "en",
    "title": "Site Configuration",
    "links": {
      "self": {
        "href": "http://acmecorp-cms.lndo.site/en/jsonapi/node/site_configuration/f8895943-7f51-451b-bb8f-a479853f1b4b?resourceVersion=id%3A230"
      }
    },
    "field_logo": {
      "type": "file--file",
      "id": "551ec1b9-b0c6-4649-bb7c-b6ebb09354ff",
      "langcode": "en",
      "uri": {
        "value": "public://2020-07/acmecorp-logo-colour-2x.png",
        "url": "http://acmecorp.oss-cn-hongkong.aliyuncs.com/s3fs-public/2020-07/acmecorp-logo-colour-2x.png"
      },
      "filemime": "image/png",
      "filesize": 54952,
      "links": {
        "self": {
          "href": "http://acmecorp-cms.lndo.site/en/jsonapi/file/file/551ec1b9-b0c6-4649-bb7c-b6ebb09354ff"
        }
      }
    },
    "relationshipNames": [
      "field_logo"
    ]
  }
]
```

As seen, the `meta` object along with `alt: "ACME Corp Logo"` is gone.

**Comment by ericwong3** [comment]
As a temporary fix, I created a patch:

```patch
diff --git a/node_modules/jsona/lib/builders/JsonDeserializer.js b/node_modules/jsona/lib/builders/JsonDeserializer.js
index 80d3ebf..6afca47 100644
--- a/node_modules/jsona/lib/builders/JsonDeserializer.js
+++ b/node_modules/jsona/lib/builders/JsonDeserializer.js
@@ -81,11 +81,13 @@ var JsonDeserializer = /** @class */ (function () {
                             return;
                         }
                         var dataItem = this.buildDataFromIncludedOrData(relationItem.id, relationItem.type);
+                        if(relationItem.meta) dataItem.meta = relationItem.meta;
                         readyRelations[k].push(this.buildModelByData(dataItem));
                     }
                 }
                 else if (relation.data) {
                     var dataItem = this.buildDataFromIncludedOrData(relation.data.id, relation.data.type);
+                    if(relation.data.meta) dataItem.meta = relation.data.meta;
                     readyRelations[k] = this.buildModelByData(dataItem);
                 }
                 else if (relation.data === null) {
```

Put this file in `patches/jsona+1.5.2.patch` and install and configure [patch-package](https://www.npmjs.com/package/patch-package).

**Comment by olosegres** [comment]
@ericwong3 
Hi. This field was not supported. I added its support in version 1.7.0, the meta should be stored in a field called relationMeta (so as not to conflict with meta from data)

**Comment by olosegres** [comment]
see 917a9a86107ada1e5a932d652864aa7aaaed7a41

**Comment by ericwong3** [comment]
Thanks for the rapid response. However, upgraded to 1.7.0 and still wouldn't work :s

**Comment by olosegres** [comment]
@ericwong3 
Sorry, I got confused and added meta processing at the wrong level.
Upgrade to 1.8.0 please

**Comment by coatezy** [comment]
Hey @olosegres, I'm trying to use your meta property implementation with a relationship data collection but the resourceIdObjMeta property is not being set on the relationship once deserialized. I've tested on a single data relationship and I'm still not seeing the resourceIdObjMeta property.

I've had a look at your tests and I can't see anything obvious to indicate why it would not be working. 😕 

Using version 1.8.0.

Example input json:

```
{
  "type": "organization",
  "id": 1.
  "attributes":{}
  "relationships": {
    "members": {
      "data": [ { "type": "user", "id": 1, "meta": { "foo": "bar" } } ]
    }
  }
}
```

```
{
  "type": "organization",
  "id": 1.
  "attributes":{}
  "relationships": {
    "member": {
      "data": { "type": "user", "id": 1, "meta": { "foo": "bar" } }
    }
  }
}
```

**Comment by coatezy** [comment]
Hmm odd. If I change my relationship id to anything greater than 1 it works. 🤔 Even if there is not an object with a matching id in the included collection. I'm pretty sure I'm not doing anything silly here, but it's more than likely. 😄

**Comment by coatezy** [comment]
I see the problem. I am using the same user include in a relationship 1 level above which does not include the meta, so that is clearing out the meta property. By changing the id in the relationship where I need the meta, the relationships are no longer overwriting each another.

Is this expected behaviour? I can give a better example if needed.

**Comment by olosegres** [comment]
@coatezy 
Hi, using your example, both items converts to objects with resourceIdObjMeta
https://runkit.com/olosegres/5f99e90cad8e200013e42e0c

**Comment by coatezy** [comment]
Hey @olosegres! Thanks for checking! 😄 As per my latest comment, I've found the issue and I can get the resourceIdObjMeta to work. My issue is probably due to the way that I'm trying to use the JSON API to create reusable fragments to mock scenarios in a mock API to carry out E2E tests in a native application.

I've attached a better example so you can see my data object. You will notice that user2 relation contains the resourceIdObjMeta attribute, but user1 does not as it is being included in another relationship one level higher without the meta attribute being set.

https://runkit.com/5f99eba543333e001aae7d26/5f99ebb0508e820013d737a8
