### ISSUE TITLE
Cannot find module 'Jsona

### ISSUE THREAD

**Issue by biaogebusy** [olosegres/jsona#42]
github build issue: 
Error: src/app/node/case/case.component.ts:2:19 - error TS2307: Cannot find module 'Jsona' or its corresponding type declarations.

In the angular component:
import Jsona from 'Jsona';

in local dev is ok, but github build have issue.

**Comment by olosegres** [comment]
@biaogebusy
Hi, there was may be not correct type reference in package.json, try to update to jsona@1.9.2
