### ISSUE TITLE
Source map issue?

### ISSUE THREAD

**Issue by samysadi** [olosegres/jsona#51]
Hello,

I am getting several similar issues :
`WARNING in ./node_modules/jsona/lib/Jsona.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from './node_modules/jsona/src/Jsona.ts' file: Error: ENOENT: no such file or directory, open './node_modules/jsona/src/Jsona.ts'`

The npm package is missing the src folder?

Edit: this message comes from webpack when running CRA build script (https://github.com/facebook/create-react-app/discussions/11767) and might indicate a source map misconfiguration in this package.

**Comment by olosegres** [comment]
Hi, src is excluded as it's common practise to put only built files to npm package. 

Source map files exist inside lib folder. 
May be there is some misconfuguration in package.json, but I'm not sure.

How do you import jsona package?

**Comment by samysadi** [comment]
Hello,

Thank you for taking time to answer this.

I import it through a regular static import statement.

The package is working perfectly fine and this may be considered a low priority issue.
There is just this annoying warning issued by webpack when running the start script of create-react-app (check the link I sent before).

If not including the src folder, maybe it's worth considering not building the sourcemaps since they reference it (in tsconfig.json)?

Regards.

**Comment by olosegres** [comment]
Fixed in version `1.11.0` 
Please check and reopen issue if necessary
