### ISSUE TITLE
When serializing with includeNames, only the first element of array is included in the resulting body if elements don't have id

### ISSUE THREAD

**Issue by marcoherrerarendon** [olosegres/jsona#55]
Awesome job with this library!

As the title states, only the first element of the array is included when the elements don't have an id. I would expect all elements to be included.

According to the JSONAPI spec, included resources do not need to contain an id field. See [here](https://jsonapi.org/format/#document-resource-objects) for more information.

I created a [unit test](https://github.com/marcoherrerarendon/jsona/blob/master/tests/Jsona.test.ts#L56) that showcases the issue. Feel free to clone and run the test.

**Comment by olosegres** [comment]
Fixed in version `1.11.0` 
Please check and reopen issue if necessary
