### ISSUE TITLE
Incompatible with react-query

### ISSUE THREAD

**Issue by kcsujeet** [olosegres/jsona#65]
# Description 
It seems like it causes circular dependency and thus causes incompatibility with react query. Discussion [here](https://github.com/TanStack/query/discussions/6025). 

# Replication
[link](https://codesandbox.io/s/throbbing-bash-cxzhrt?file=/api.ts)

**Comment by olosegres** [comment]
Hi, actually Jsona is designed to use circular relationships.

You can look at original implementation here https://github.com/olosegres/jsona/blob/c7fb018ac08a35babe67fdd34695c57720f4baa1/src/simplePropertyMappers.ts#L122

You have few choices:
- move deserialization somewhere to hook, after raw data is processed by react-query
- modify process of properties mapping via extending JsonPropertiesMapper and use some special implementation of setRelationships method or defineRelationGetter (jsona is extanable ```const dataFormatter = new Jsona({ jsonPropertiesMapper: MyJsonPropertiesMapper });```)

**Comment by kcsujeet** [comment]
@olosegres thank you for the reply. can you provide an example of how to do this?

**Comment by olosegres** [comment]
> @olosegres thank you for the reply. can you provide an example of how to do this?

To do what? extend jsona? It is briefly described in the readme https://github.com/olosegres/jsona#customize

But I highly recommend you to use my first suggestion - move deserialization from the interceptor to custom hook. Something like useJsonApiFetch where you will get data from api and convert it to deserialized version.

**Comment by kcsujeet** [comment]
# For future references:

I was able to solve this problem by changing this line `model[propName] = relationships[propName]` in `setRelationships` method. 

In `myCustomMapper.ts`, everything same as [link](https://github.com/olosegres/jsona/blob/c7fb018ac08a35babe67fdd34695c57720f4baa1/src/simplePropertyMappers.ts#L94C27-L94C27), except for the line mentioned above. 

Then just use the custom mapper as:

```
import { JsonPropertiesMapper } from 'utils/myCustomMapper

const dataFormatter = new Jsona({
  jsonPropertiesMapper: new JsonPropertiesMapper()
})
```
