### ISSUE TITLE
Generic support

### ISSUE THREAD

**Issue by artem-galas** [olosegres/jsona#8]
Hi. Thanks for the nice package. 
I want to use it, but I think it would be good to add supporting of generic. 
What do you think?

For Example:
```ts
const jsona = new Jsona();
jsona.deserialize<MyModel[]>(apiResponse);
```

**Comment by olosegres** [comment]
Hi, I think it will be useful!
I can implement it myself after a while, but it will be cool if you make an PR :)

**Comment by olosegres** [comment]
@artem-galas 
`TJsonaModel` uses not only to build top model in `jsona.deserialize`, but to build it's relations too (in  `JsonDeserializer`), and I see no way what to do with it.

May be you have some idea?

It seems to me, that type casting is a good compromise

**Comment by artem-galas** [comment]
@olosegres I've just pushed a WIP branch with generic support. You can check. I've just added 
`<T extends TJsonaModel>` for `deserialize` and `build` methods. 
https://github.com/artem-galas/jsona/tree/generic_support

What do you think?

As I understand, we need add generic support for more function.

**Comment by olosegres** [comment]
@artem-galas 
Seems to be ok, but `jsona.deserialize` and `JsonDeserializer.build` may return `Array<TJsonaModel>`, so I think in return type should be `T | Array<T>`

**Comment by olosegres** [comment]
I thought you will made another commit, but..

I have tried to apply support of generic to deserialize & build, that returns mixed type (TJsonaModel | Array<TJsonaModel), and realized, that you still need type casting, like this:
```
const userModel: IUser = <IUser>jsona.deserialize<IUser>({data: user2.json});
```  
Is it not overhead?

May be
```
const userModel = <IUser>jsona.deserialize({data: user2.json});
```
will enough?

**Comment by artem-galas** [comment]
@olosegres 
Yes you're right it's a little bit overhead.
I using TypeCasting and I'm happy with them. I think generic support not require. 
What do you think?

**Comment by olosegres** [comment]
In this case I don't see any other way how to tell to TS a real type of returned data.
In any other case I would prefer generics
